language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
install:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: progressive-cards/progressive-cards.github.io
  target_branch: master
  local_dir: docs
  on:
    branch: master
