language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
install:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
